import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ThemeProvider } from "~/components/theme-provider";
import {
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuTrigger,
  NavigationMenuContent,
  navigationMenuTriggerStyle,
} from "~/components/ui/navigation-menu";
import Link from "next/link";
import { ThemeToggle } from "~/components/theme-provider";
// import { CircuitBackground } from "~/components/circuit-background";

export const metadata: Metadata = {
  title: "Create ButT3r App",
  description: "Generated by ButT3r using create-t3-app :P",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <ThemeProvider className="bg-gradient-to-b from-[#57aed1] to-[#2e026d] dark:from-[#2e026d] dark:to-[#57aed1]">
        {/* <CircuitBackground /> */}
        <nav className="fixed left-0 right-0 top-0 bg-white/10 p-4 backdrop-blur-md">
          <div className="mx-auto max-w-7xl">
            <NavigationMenu>
              <NavigationMenuList className="flex justify-center">
                <NavigationMenuItem>
                  <Link href="/" legacyBehavior passHref>
                    <NavigationMenuLink
                      className={`${navigationMenuTriggerStyle()} text-gray-900 hover:text-gray-700 dark:text-white dark:hover:text-gray-300`}
                    >
                      BT3r
                    </NavigationMenuLink>
                  </Link>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuTrigger
                    className={`${navigationMenuTriggerStyle()} text-gray-900 hover:text-gray-700 dark:text-white dark:hover:text-gray-300`}
                  >
                    Docs
                  </NavigationMenuTrigger>
                  <NavigationMenuContent className="bg-white/90 backdrop-blur-md dark:bg-gray-800/90">
                    <ul className="grid w-[400px] gap-3 p-4 md:w-[500px] md:grid-cols-2 lg:w-[600px]">
                      <li>
                        <Link
                          href="https://create.t3.gg/docs"
                          legacyBehavior
                          passHref
                        >
                          <NavigationMenuLink
                            className={`${navigationMenuTriggerStyle()} text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700`}
                          >
                            T3 Docs
                          </NavigationMenuLink>
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="https://nextjs.org/docs"
                          legacyBehavior
                          passHref
                        >
                          <NavigationMenuLink
                            className={`${navigationMenuTriggerStyle()} text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700`}
                          >
                            Next.js Docs
                          </NavigationMenuLink>
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="https://tailwindcss.com/docs"
                          legacyBehavior
                          passHref
                        >
                          <NavigationMenuLink
                            className={`${navigationMenuTriggerStyle()} text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700`}
                          >
                            Tailwind Docs
                          </NavigationMenuLink>
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="https://ui.shadcn.com/docs"
                          legacyBehavior
                          passHref
                        >
                          <NavigationMenuLink
                            className={`${navigationMenuTriggerStyle()} text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700`}
                          >
                            Shadcn Docs
                          </NavigationMenuLink>
                        </Link>
                      </li>
                      <li>
                        <Link href="/docs" legacyBehavior passHref>
                          <NavigationMenuLink
                            className={`${navigationMenuTriggerStyle()} text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700`}
                          >
                            ButT3r Docs
                          </NavigationMenuLink>
                        </Link>
                      </li>
                    </ul>
                  </NavigationMenuContent>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <Link
                    href="https://github.com/your-repo"
                    legacyBehavior
                    passHref
                  >
                    <NavigationMenuLink
                      className={`${navigationMenuTriggerStyle()} text-gray-900 hover:text-gray-700 dark:text-white dark:hover:text-gray-300`}
                    >
                      GitHub
                    </NavigationMenuLink>
                  </Link>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <ThemeToggle />
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
          </div>
        </nav>
        <div className="mc">{children}</div>
      </ThemeProvider>
    </html>
  );
}
